services:
  mono-back:
    build:
      context: .
      dockerfile: src/main/docker/Dockerfile.jvm
    ports:
      - "8080:8080"
    depends_on:
      - mono-postgres
    environment:
      - QUARKUS_DATASOURCE_JDBC_URL=jdbc:postgresql://mono-postgres:5432/monodb
      - QUARKUS_DATASOURCE_USERNAME=user
      - QUARKUS_DATASOURCE_PASSWORD=password

  mono-postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: monodb
    ports:
      - "5432:5432"
